# Generated by Django 3.0.7 on 2025-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='tin',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='salebill',
            name='tin',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tin',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
