# Generated by Django 3.0.7 on 2025-11-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20251130_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tin',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
